from __future__ import annotations

import shutil
import sqlite3
import time
import uuid
from pathlib import Path

from tools import daily_report as dr


def _mk_local_tmp() -> Path:
    p = Path("localtests") / f"daily_report_{uuid.uuid4().hex[:8]}"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _build_trades_db(path: Path, *, rows: list[tuple[float, float]]) -> None:
    conn = sqlite3.connect(str(path))
    try:
        conn.execute("CREATE TABLE trades (exit_time REAL, pnl_bps REAL)")
        conn.executemany("INSERT INTO trades(exit_time,pnl_bps) VALUES (?,?)", rows)
        conn.commit()
    finally:
        conn.close()


def test_daily_report_writes_file_with_anomalies(monkeypatch) -> None:
    tmp = _mk_local_tmp()
    try:
        db = tmp / "paper_trades.db"
        out_dir = tmp / "reports"
        now = time.time()
        # All trades inside today, strongly negative and low win-rate.
        _build_trades_db(
            db,
            rows=[
                (now - 60, -40.0),
                (now - 50, -20.0),
                (now - 40, 5.0),
            ],
        )
        monkeypatch.setattr(
            "sys.argv",
            ["x", "--db", str(db), "--out-dir", str(out_dir)],
        )
        rc = dr.main()
        assert rc == 0
        today = time.strftime("%Y-%m-%d", time.gmtime())
        # Use actual UTC date generated by script.
        out_files = list(out_dir.glob("*.md"))
        assert out_files, "daily report file not generated"
        txt = out_files[0].read_text(encoding="utf-8")
        assert "Daily Report" in txt
        assert "Anomalies:" in txt
        assert "low_win_rate" in txt
        assert "deep_negative_day" in txt
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

