"""Canonical AMI enums — whitepaper Appendix A/B/C + Part XII."""
from __future__ import annotations
from enum import Enum


class KnowledgeStatus(str, Enum):
    OBSERVATION = "OBSERVATION"
    OPEN_QUESTION = "OPEN_QUESTION"
    HYPOTHESIS = "HYPOTHESIS"
    TESTING = "TESTING"
    PRELIMINARY = "PRELIMINARY"
    REPLICATED = "REPLICATED"
    HOLDOUT_VALIDATED = "HOLDOUT_VALIDATED"
    FORWARD_VALIDATING = "FORWARD_VALIDATING"
    OPERATIONAL_CANDIDATE = "OPERATIONAL_CANDIDATE"
    PROVISIONALLY_ACCEPTED = "PROVISIONALLY_ACCEPTED"
    REGIME_LIMITED = "REGIME_LIMITED"
    CONTRADICTED = "CONTRADICTED"
    WEAKENED = "WEAKENED"
    DEPRECATED = "DEPRECATED"
    REJECTED = "REJECTED"
    RETRY_WHEN_CONDITIONS_CHANGE = "RETRY_WHEN_CONDITIONS_CHANGE"


# Promotion ladder (Part XII §23) — index = rank
PROMOTION_LADDER = [
    KnowledgeStatus.OBSERVATION, KnowledgeStatus.HYPOTHESIS, KnowledgeStatus.TESTING,
    KnowledgeStatus.PRELIMINARY, KnowledgeStatus.REPLICATED, KnowledgeStatus.HOLDOUT_VALIDATED,
    KnowledgeStatus.FORWARD_VALIDATING, KnowledgeStatus.OPERATIONAL_CANDIDATE,
    KnowledgeStatus.PROVISIONALLY_ACCEPTED,
]


class Permission(str, Enum):
    RESEARCH_ONLY = "RESEARCH_ONLY"
    BACKTEST_ALLOWED = "BACKTEST_ALLOWED"
    SHADOW_ALLOWED = "SHADOW_ALLOWED"
    OBSERVER_ALLOWED = "OBSERVER_ALLOWED"
    PAPER_ALLOWED = "PAPER_ALLOWED"
    OPERATIONAL_CANDIDATE = "OPERATIONAL_CANDIDATE"
    LIVE_ALLOWED = "LIVE_ALLOWED"
    SIZING_ALLOWED = "SIZING_ALLOWED"
    PORTFOLIO_ALLOWED = "PORTFOLIO_ALLOWED"


# Minimum status rank required for each permission (governor enforces)
PERMISSION_MIN_STATUS = {
    Permission.RESEARCH_ONLY: KnowledgeStatus.OBSERVATION,
    Permission.BACKTEST_ALLOWED: KnowledgeStatus.PRELIMINARY,
    Permission.SHADOW_ALLOWED: KnowledgeStatus.REPLICATED,
    Permission.OBSERVER_ALLOWED: KnowledgeStatus.REPLICATED,
    Permission.PAPER_ALLOWED: KnowledgeStatus.HOLDOUT_VALIDATED,
    Permission.OPERATIONAL_CANDIDATE: KnowledgeStatus.FORWARD_VALIDATING,
    Permission.LIVE_ALLOWED: KnowledgeStatus.OPERATIONAL_CANDIDATE,
    Permission.SIZING_ALLOWED: KnowledgeStatus.PROVISIONALLY_ACCEPTED,
    Permission.PORTFOLIO_ALLOWED: KnowledgeStatus.OPERATIONAL_CANDIDATE,
}


class ClaimType(str, Enum):
    DESCRIPTIVE = "DESCRIPTIVE"
    PREDICTIVE = "PREDICTIVE"
    MECHANISTIC = "MECHANISTIC"
    CAUSAL = "CAUSAL"
    OPERATIONAL = "OPERATIONAL"
    META_RESEARCH = "META_RESEARCH"


class EvidenceLevel(int, Enum):
    ANECDOTAL = 0
    IN_SAMPLE = 1
    CHRONOLOGICAL = 2
    UNTOUCHED_HOLDOUT = 3
    INDEPENDENT_REPLICATION = 4
    FORWARD_SHADOW = 5
    CONTROLLED_PAPER = 6
    SMALL_SCALE_OPERATIONAL = 7
    MULTI_REGIME = 8
    CROSS_MARKET = 9


class DataQuality(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    STALE = "STALE"
    GAPPED = "GAPPED"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    UNVERIFIED = "UNVERIFIED"
    RECONSTRUCTED = "RECONSTRUCTED"
    UNAVAILABLE = "UNAVAILABLE"


class FailureType(str, Enum):
    NO_EDGE = "NO_EDGE"
    OVERFIT = "OVERFIT"
    LOOKAHEAD = "LOOKAHEAD"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
    REGIME_LIMITED = "REGIME_LIMITED"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    DUPLICATE_HYPOTHESIS = "DUPLICATE_HYPOTHESIS"
    WRONG_TIMEFRAME = "WRONG_TIMEFRAME"
    WRONG_DIRECTION = "WRONG_DIRECTION"


class BeliefRevision(str, Enum):
    REINFORCE = "REINFORCE"
    RESTRICT = "RESTRICT"
    REVISE = "REVISE"
    REJECT = "REJECT"


class Action(str, Enum):
    OBSERVE = "OBSERVE"
    RESEARCH = "RESEARCH"
    WAIT = "WAIT"
    NO_TRADE = "NO_TRADE"
    OPEN_LONG = "OPEN_LONG"
    OPEN_SHORT = "OPEN_SHORT"
    HOLD = "HOLD"
    SCALE = "SCALE"
    REDUCE = "REDUCE"
    LOCK = "LOCK"
    EXIT = "EXIT"
    REVERSE = "REVERSE"
    PAUSE = "PAUSE"
    DEMOTE = "DEMOTE"
    PROMOTE = "PROMOTE"
    RETEST = "RETEST"
    EXPIRE = "EXPIRE"


# Which permission each operational action requires (governor consults this)
ACTION_REQUIRED_PERMISSION = {
    Action.OBSERVE: Permission.RESEARCH_ONLY,
    Action.RESEARCH: Permission.RESEARCH_ONLY,
    Action.WAIT: Permission.RESEARCH_ONLY,
    Action.NO_TRADE: Permission.RESEARCH_ONLY,
    Action.OPEN_LONG: Permission.LIVE_ALLOWED,
    Action.OPEN_SHORT: Permission.LIVE_ALLOWED,
    Action.HOLD: Permission.SHADOW_ALLOWED,
    Action.SCALE: Permission.SIZING_ALLOWED,
    Action.REDUCE: Permission.SIZING_ALLOWED,
    Action.LOCK: Permission.SHADOW_ALLOWED,
    Action.EXIT: Permission.LIVE_ALLOWED,
    Action.REVERSE: Permission.LIVE_ALLOWED,
}


class StateFamily(str, Enum):
    GLOBAL_STATE = "GLOBAL_STATE"
    REGIME_STATE = "REGIME_STATE"
    SESSION_STATE = "SESSION_STATE"
    STRUCTURE_STATE = "STRUCTURE_STATE"
    MICROSTRUCTURE_STATE = "MICROSTRUCTURE_STATE"
    BOOK_STATE = "BOOK_STATE"
    MAKER_STATE = "MAKER_STATE"
    FLOW_STATE = "FLOW_STATE"
    LEVERAGE_STATE = "LEVERAGE_STATE"
    NETWORK_STATE = "NETWORK_STATE"
    PRESSURE_STATE = "PRESSURE_STATE"
    CASCADE_STATE = "CASCADE_STATE"
    LONG_STATE = "LONG_STATE"
    SHORT_STATE = "SHORT_STATE"
    TRADE_STATE = "TRADE_STATE"
    POSITION_STATE = "POSITION_STATE"
    EXIT_STATE = "EXIT_STATE"
    PORTFOLIO_STATE = "PORTFOLIO_STATE"
    KNOWLEDGE_STATE = "KNOWLEDGE_STATE"
    RESEARCH_STATE = "RESEARCH_STATE"


class StructurePhase(str, Enum):
    ACCUMULATION = "ACCUMULATION"
    COMPRESSION = "COMPRESSION"
    EARLY_EXPANSION = "EARLY_EXPANSION"
    EXPANSION = "EXPANSION"
    MATURE_TREND = "MATURE_TREND"
    DISTRIBUTION = "DISTRIBUTION"
    BREAKDOWN = "BREAKDOWN"
    CASCADE = "CASCADE"
    EXHAUSTION = "EXHAUSTION"
    ABSORPTION = "ABSORPTION"
    RECLAIM = "RECLAIM"
    RECOVERY = "RECOVERY"
    REACCUMULATION = "REACCUMULATION"
    REVERSAL = "REVERSAL"
    RANGE = "RANGE"
    DISLOCATION = "DISLOCATION"


class TradeLifecycleState(str, Enum):
    OPEN = "OPEN"
    HEALTHY = "HEALTHY"
    ACCELERATING = "ACCELERATING"
    STALLING = "STALLING"
    WEAKENING = "WEAKENING"
    EXHAUSTED = "EXHAUSTED"
    RECOVERING = "RECOVERING"
    LOCKED = "LOCKED"
    REVERSING = "REVERSING"
    INVALIDATED = "INVALIDATED"
    CLOSED = "CLOSED"


class CascadePhase(str, Enum):
    PRE_CASCADE = "PRE_CASCADE"
    EARLY_CASCADE = "EARLY_CASCADE"
    ACCELERATION = "ACCELERATION"
    PEAK = "PEAK"
    EXHAUSTION = "EXHAUSTION"
    RECOVERY = "RECOVERY"
    SECONDARY_ECHO = "SECONDARY_ECHO"
    FAILED_CASCADE = "FAILED_CASCADE"
    NONE = "NONE"


TIMEFRAMES = ["1m", "5m", "15m", "1h", "4h", "1D", "1W"]
TIMEFRAME_MS = {"1m": 60_000, "5m": 300_000, "15m": 900_000, "1h": 3_600_000,
                "4h": 14_400_000, "1D": 86_400_000, "1W": 604_800_000}
