# -*- coding: utf-8 -*-
"""D-E35 -- the EXTERNAL covariate D-E34 could not build, now that t0 is exposed.

D-E34 found two independent selection channels on covariates that were already inside the frozen
construction: pre-anchor volatility (rho -0.1502) and the episode's own size (rho +0.1532).  Both
are properties of the symbol's own process.  The question D-E33 actually asked -- is the selection
on MARKET-WIDE activity -- needed a cross-symbol window and therefore t0, which `collect()` did not
expose.  It does now, added additively and verified byte-identical on everything computed.

WHY THE DISTINCTION IS THE CORPUS'S, NOT MINE.  ABG: *"we tacitly assume that all covariates are
predictable ... the value at time t of a time-dependent covariate should be known just before time
t"*, and it sends the internal/external question to Kalbfleisch and Prentice 6.3.  An EXTERNAL
covariate is one not generated by the individual's own event process.  That is exactly the line
between the two covariates built here:

  own_prior   episodes of the SAME symbol in [t0 - W, t0).  INTERNAL: the same process that
              produces the INTERRUPTED event also produces this count.
  mkt_prior   episodes of the OTHER symbols in [t0 - W, t0).  EXTERNAL: another symbol's
              liquidations are not this spell's event process.

Both are measured STRICTLY BEFORE t0.  A window through t0 would count the very episode that
defines the anchor, and a forward window would count the arrival that IS the INTERRUPTED event.

IDENTIFIABILITY, NAMED BECAUSE IT IS NOT FREE.  A market-wide measure is shared by every spell
alive at the same calendar moment, so it could not be separated from a calendar-time baseline if
all spells ran on the same clock.  They do not: spells are staggered across 24 days and three
symbols, so two spells with the same elapsed u sit at different calendar times and therefore at
different mkt_prior.  That stagger is what makes the covariate identifiable here, and it is a
property of this sample rather than of the method.

STATISTIC.  The one D-E34 validated: Spearman rank correlation against spell duration, permutation
null, grid-free.  It is re-validated here on its own known-positive ladder rather than inherited,
because the covariate is new even though the statistic is not.

SCOPE FENCE.  Outcome-blind.  D-E8's frozen estimand untouched; mu_tau not recomputed; no
threshold selected.

Usage:  python tools/d_e35_external_covariate_v1.py
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from tools.d_e11_p2_p3_v1 import collect                       # noqa: E402
from tools.d_e8_evaluator_v1 import (                           # noqa: E402
    FLOOR_PRIMARY, K_BPS, assert_spec_unchanged)
from tools.d_e33_interrupt_vs_arrival_v1 import episode_starts  # noqa: E402
from tools.d_e34_selection_on_activity_v1 import ladder, rho    # noqa: E402

W_MS = 6 * 3600 * 1000          # declared look-back, strictly before t0
OUT = os.path.join(ROOT, "reports", "atlas", "D_E35_EXTERNAL_COVARIATE_V1.json")
SEED = 20260827
NULL_SIMS = 2000


def prior_counts(t0, sym, eps):
    """Episodes in [t0 - W, t0), split same-symbol vs other-symbol.  Never through t0."""
    own = other = 0
    for s, v in eps.items():
        lo = np.searchsorted(v, t0 - W_MS, side="left")
        hi = np.searchsorted(v, t0, side="left")               # STRICTLY before
        n = int(hi - lo)
        if s == sym:
            own += n
        else:
            other += n
    return own, other


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    h = assert_spec_unchanged()
    print("D-E35  the EXTERNAL covariate   prereg sha256 %s VERIFIED" % h[:16])
    print("       look-back %dh, STRICTLY before t0.  own = INTERNAL, mkt = EXTERNAL (ABG / K&P 6.3)\n"
          % (W_MS / 3600000))

    rows = collect(FLOOR_PRIMARY, K_BPS)
    eps = episode_starts(FLOOR_PRIMARY)
    t = np.array([r["t_ms"] for r in rows], float)
    own = np.empty(len(rows))
    mkt = np.empty(len(rows))
    for i, r in enumerate(rows):
        own[i], mkt[i] = prior_counts(int(r["t0_ms"]), r["sym"], eps)

    sig = np.array([r["sigma_1s"] for r in rows], float)
    qv = np.array([r["qv"] for r in rows], float)
    rng = np.random.default_rng(SEED)

    res = {"prereg_sha256": h, "n": len(rows), "lookback_h": W_MS / 3600000,
           "answers": "D-E33 market-wide question", "covariates": {}}

    print("  %-11s %-10s %8s %9s %9s %7s   %s"
          % ("covariate", "kind", "mean", "rho", "p_low", "z", "reading"))
    for name, cov, kind in (("own_prior", own, "INTERNAL"), ("mkt_prior", mkt, "EXTERNAL")):
        obs = rho(cov, t)
        nulls = np.array([rho(rng.permutation(cov), t) for _ in range(NULL_SIMS)])
        z = (obs - nulls.mean()) / nulls.std(ddof=1)
        p_lo = float((nulls <= obs).mean())
        lad = ladder(t, cov, rng)
        mono = all(lad[i]["rho"] >= lad[i + 1]["rho"] for i in range(len(lad) - 1))
        reading = ("LADDER_FAILED_RESULT_UNREADABLE" if not mono else
                   ("SURVIVORS_SIT_IN_QUIETER_WINDOWS" if p_lo < 0.025 else
                    ("SURVIVORS_SIT_IN_BUSIER_WINDOWS" if p_lo > 0.975 else
                     "NOT_DISTINGUISHABLE_FROM_CHANCE")))
        res["covariates"][name] = {"kind": kind, "mean": round(float(cov.mean()), 3),
                                   "spearman_rho": round(obs, 5), "z": round(float(z), 2),
                                   "one_sided_p_low": round(p_lo, 4),
                                   "known_positive_ladder": lad, "ladder_monotone": mono,
                                   "reading": reading}
        print("  %-11s %-10s %8.2f %9.4f %9.4f %7.2f   %s"
              % (name, kind, cov.mean(), obs, p_lo, z, reading))
        print("     ladder: %s   monotone=%s"
              % (" ".join("%.2f:%+.3f" % (x["strength"], x["rho"]) for x in lad), mono))

    # is the EXTERNAL channel the same thing as the two D-E34 found, or a third?
    pair = {"mkt_vs_own": round(rho(mkt, own), 4),
            "mkt_vs_sigma_1s": round(rho(mkt, sig), 4),
            "mkt_vs_qv": round(rho(mkt, qv), 4),
            "own_vs_sigma_1s": round(rho(own, sig), 4)}
    res["covariate_correlations"] = pair
    print("\n  IS IT A THIRD CHANNEL OR THE SAME ONE?  rank correlations between covariates")
    for k, v in pair.items():
        print("     %-18s %+0.4f" % (k, v))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(res, indent=1))
    print("\nwrote %s" % OUT)


if __name__ == "__main__":
    main()
